name: "GT Holidays Tour Booking & Payment Systems"

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug OIDC claims
        run: echo "${{ github.actor }} from ${{ github.repository }} on ${{ github.ref }}"

      - name: Print OIDC token
        run: |
          echo "GitHub repository: ${{ github.repository }}"
          echo "GitHub ref: ${{ github.ref }}"
          TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
               $ACTIONS_ID_TOKEN_REQUEST_URL)
          echo "OIDC token (truncated): ${TOKEN:0:100}..."


      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::586308082177:role/gokilatestdeployrole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./tf

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./tf